from datetime import datetime, timedelta
import ahocorasick
from pyrogram import filters, enums
from pyrogram.types import InlineKeyboardButton, InlineKeyboardMarkup

from Banword import Banword as app

# List of 18+ or abusive words (expandable)
BAD_WORDS = [
    # 18+ related words
    "18+",
    "sex",
    "porn",
    "nude",
    "blowjob",
    "boobs",
    "bobs",
    "condom",
    "xxx",
    "adult",
    "nangi",
    "randi",
    # Common gaaliyan & offensive words (Hindi/English)
    "chutiya",
    "madarchod",
    "bhenchod",
    "gaand",
    "gand",
    "lund",
    "ch**d",
    "g***i",
    "harami",
    "kutte",
    "boor",
    "chuchi",
    "kutta",
    "gandu",
    "madharchod",
    "lundoo",
    "lodu",
    "bhains",
    "chod",
    "randi",
    "randa",
    "haramzada",
    "randi ka bacha",
    "bhosdiwala",
    "bhosdike",
    "mc",
    "mcchod",
    "randi ki aulaad",
    "gand mara",
    "lund mar",
    "lauda",
    "loda",
    "chodu",
    "chut",
    "chutiyapa",
    "chutiye",
    "chut ke",
    "chut ke laude",
    "chut ke bache",
    "bhosadike",
    # Slang variations with stars (to catch censored forms)
    "ch**d",
    "g***i",
    "m**ch*d",
    "b**chod",
    "b***chod",
] + [
    "sex",
    "porn",
    "nude",
    "fuck",
    "bitch",
    "dick",
    "pussy",
    "slut",
    "boobs",
    "cock",
    "asshole",
    "chudai",
    "rand",
    "chhinar",
    "sexy",
    "hot girl",
    # ✅ Common Hindi Gaaliyan in English Font
    "chutiya",
    "madarchod",
    "Madhrachod",
    "Madharchod",
    "betichod",
    "behenchod",
    "gandu",
    "randi",
    "bhosdi",
    "hijda",
    "lund",
    "chod",
    "jhaatu",
    "harami",
    "kamina",
    "saala",
    "gand",
    "pagal",
    "bhadwa",
    "chut",
    "bevkoof",
    "nikkamma",
    "haramkhor",
    "chaalu",
    "fattuu",
    "dhakkan",
    "gadha",
    "kutta",
    "suvar",
    "besharam",
    "bhosdike",
    "teri maa ki chut",
    "teri behan ki chut",
    "randi ka bacha",
    "chinal ka bacha",
    "gb road pe teri ma show karti",
    "gb road ke paidaish",
    "teri ma ka boor",
    "teri ma ka boor fadhu",
    "teri ma ki chut mai ungali kardu",
    "teri bahan ki chut fadhu",
    "teri bahan ki gand mai ungali karu",
    "teri bahan ki boor ungali karu",
    "teri bahan meri rakhail",
    "teri ma meri rakhail",
    "Dm karo baby",
    "Inbox karo baby",
    "private group chalogi baby",
    "tera porn banauga",
    "tera hot video viral karunga",
    "Ruk Madhar chodh",
    "sale",
    "Randi ke pille tore ma ko chodho",
    "chutad",
    "haramzaada",
    "haram ki aulaad",
    "suvar ka baccha",
    "gand ka keeda",
    "chirkut",
    "ghatiya",
    "sadela",
    "choor",
    "lutera",
    "chichora",
    "badtameez",
    "baddimag",
    "fraud",
    "nalayak",
    "bewda",
    "sandass",
    "ganda",
    "dhongi",
    "bhikhari",
    "faltu",
    "kachra",
    "pagal kutta",
    "badmash",
    "aalsi",
    "kanjoos",
    "ghamandi",
    "farzi",
    "dhurt",
    "bakchod",
    "gappi",
    "nakli",
    "chalu",
    "lafanga",
    "bakwas",
    "bikau",
    "chapri",
    "nalla",
    "tatti",
    "jhantu",
    "ullu ka pattha",
    "ulloo",
    "chindi",
    "panauti",
    "lukkha",
    "kuttiya",
    "kaminey",
    "kamzarf",
    "budbak",
    "chirkut",
    "sust",
    "tharki",
    "bhagoda",
    "kutta kamina",
    "bhains ki aankh",
    "teri taang tod dunga",
    "teri band baja dunga",
    "tera dimaag kharab hai",
    "teri waat laga dunga",
    "teri maa ka bhosda",
    "teri gaand maar dunga",
    # ✅ Common Porn & NSFW Terms (Mix of Hindi & English)
    "sex",
    "porn",
    "nude",
    "nangi",
    "chudai",
    "bhabhi chudai",
    "sex chat",
    "sex chat karogi",
    "sex chat karogi baby",
    "lund",
    "gaand",
    "bhosda",
    "chut",
    "maal",
    "jism",
    "randi",
    "randi khana",
    "desi sex",
    "hot video",
    "nangi ladki",
    "bhabhi nudes",
    "bhabhi sex",
    "sexy aunty",
    "nude aunty",
    "bhabhi ki chut",
    "real meet",
    "viral video",
    "rape video",
    "nudes viral",
    "aunty ki chut",
    "boobs",
    "tits",
    "nipple",
    "dildo",
    "pussy",
    "vagina",
    "penis",
    "cock",
    "dick",
    "cum",
    "anal",
    "squirt",
    "deepthroat",
    "hentai",
    "bdsm",
    "lesbian",
    "gay sex",
    "futa",
    "69",
    "screwing",
    "sex chat",
    "incest",
    "stepmom",
    "stepsis",
    "stepbro",
    "honeymoon sex",
    "bhabhi nude",
    "hot indian actress",
    "desi nudes",
    "sexy saree",
    "lingerie",
    "erotic",
    "kinky",
    "naughty",
    "sensual",
    "lust",
    "muth",
    "muthi",
    "masturbation",
    "call girl",
    "escort",
    "sex worker",
    "rape porn",
    "forced porn",
    "underage porn",
    "child porn",
    "pedo",
    "loli",
    "teen sex",
    "schoolgirl porn",
    "hijab porn",
    "casting couch",
    "sex tape",
    "strip club",
    "naked",
    "uncensored",
    "bikini photos",
    "hot saree",
    "sexy photos",
    "onlyfans",
    "patreon nudes",
    "hot cam",
    "sex cam",
    "live sex",
    "private parts",
    "exposed",
    "naked selfie",
    "sex video",
    "desi sex video",
    "bollywood sex",
    "lingam massage",
    "tantra sex",
    "milf",
    "hotwife",
    "swinger",
    "erotic massage",
    "boobs press",
    "licking",
    "lick pussy",
    "moaning",
    "dirty talk",
    "hot girl",
    "big boobs",
    "tight pussy",
    "wet pussy",
    "hard cock",
    "big cock",
    "service available",
    "paid service available",
    "blowjob",
    "I am ready message me",
    "I'm full nude now",
    "Paid show",
    "video call available",
    "fuck you",
    "fuck me",
    "pussy",
    "boobs",
    "handjob",
    "sexy dance",
    "strip tease",
    "sex position",
    "saree sex",
    "sexy aunty video",
    "hot desi bhabhi",
    "bollywood hot",
    "item girl",
    "hot indian model",
    "desi randi",
    "desi call girl",
    "sexy night",
    "hijra sex",
    "chudai story",
    "sex story",
    "suhagraat sex",
    "honeymoon night",
    "love making",
    "hot romance",
    "desi romance",
    "hot chat",
    "sexy time",
    "naughty chat",
    "dirty video",
    "hidden cam",
    "bathroom sex",
    "hotel sex",
    "massage sex",
    "body to body massage",
    "saree romance",
    "choli romance",
    "cleavage show",
    "hot navel",
    "desi thighs",
    "big ass",
    "backside show",
]

AC = ahocorasick.Automaton()
for idx, word in enumerate(BAD_WORDS):
    AC.add_word(word.lower(), (idx, word))
AC.make_automaton()

cache = {}
CACHE_TTL = timedelta(minutes=10)

def contains_bad_word(text):
    return any(True for _ in AC.iter(text.lower()))

async def get_admins(chat_id):
    now = datetime.utcnow()
    if chat_id in cache:
        entry = cache[chat_id]
        if now < entry["expires"]:
            return entry["admins"]

    admins = []
    async for m in app.get_chat_members(chat_id, filter=enums.ChatMembersFilter.ADMINISTRATORS):
        admins.append(m.user.id)

    cache[chat_id] = {"admins": admins, "expires": now + CACHE_TTL}
    return admins

@app.on_message(filters.group & filters.text & ~filters.via_bot)
async def filter_18(client, message):
    text = (message.text or message.caption or "").lower().strip()
    if not text or not message.from_user:
        return

    if not contains_bad_word(text):
        return

    admin_ids = await get_admins(message.chat.id)

    if message.from_user.id in admin_ids:
        return

    try:
        await message.delete()
    except Exception:
        return

    warn_text = f"{message.from_user.mention}, 18+ messages are not allowed!"
    btn = InlineKeyboardMarkup(
        [
            [
                InlineKeyboardButton("🚀 𝗨𝗽𝗱𝗮𝘁𝗲", url="https://t.me/Team_Dns_Network"),
                InlineKeyboardButton("💬 𝗦𝘂𝗽𝗽𝗼𝗿𝘁", url="https://t.me/dns_support_group"),
            ]
        ]
    )
    await message.reply(warn_text, reply_markup=btn)
